### ISSUE TITLE
Why virtualenvwrapper?

### ISSUE THREAD

**Issue by codingbowoo** [itsnamgyu/django-two#2]
Any special reason for using ```virtualenvwrapper``` ?
I know that ```virtualenvwrapper``` is extended version of ```virtualenv```,
but why not ```venv``` ? Is it just your preference on the package?

**Comment by itsnamgyu** [comment]
Actually, I wasn't aware that `venv` was a module; it thought it was just how people refer to virtualenv...:sweat: 

I do like the idea of using a module from the Python standard library. I think that'll be the right direction for this learn-as-you-go repo. Could you update the README and send me a PR? Or maybe just a tutorial link? :smiley:

**Comment by codingbowoo** [comment]
https://packaging.python.org/guides/tool-recommendations/
Well, here it says "using virtualenv will still be recommended for users that need cross-version consistency" . I'll try to send you PR ^_^

**Comment by itsnamgyu** [comment]
Much thanks!

![alt text](https://media.giphy.com/media/3o85xHEuqHN1Pdc38Q/giphy.gif)

**Comment by itsnamgyu** [comment]
We're using venv now! Check out the documentation on [the wiki](https://github.com/itsnamgyu/django-two/wiki/Environment-Setup-on-Ubuntu-Server).
